spring:
  datasource:
    url: jdbc:postgresql://bank-registry-psql-postgresql:27017/
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
server:
  port: 8080